name: Create Tag on Merge to test

on:
  # push:
  #   branches:
  #     - test
  pull_request:
    types: [closed]
    branches:
      - test

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'test'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # - name: Create VERSION file
    #   run: echo "v1.0.0" > VERSION
      
    - name: Read version from file
      run: |
        export VERSION=$(cat jenkinsgit/VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Increment version
      run: |
        VERSION=$VERSION
        MAJOR=$(echo $VERSION | cut -d '.' -f 1 | sed 's/v//')
        MINOR=$(echo $VERSION | cut -d '.' -f 2)
        PATCH=$(echo $VERSION | cut -d '.' -f 3)

        NEW_PATCH=$((PATCH+1))

        echo "v$MAJOR.$MINOR.$NEW_PATCH" > .github/workflows/VERSION

        echo "new_version=v$MAJOR.$MINOR.$NEW_PATCH" >> $GITHUB_ENV
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add jenkinsgit/VERSION
        git commit -m "Bump version to v$MAJOR.$MINOR.$NEW_PATCH.$BUG"
        git push

    - name: Create tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.new_version }}
        release_name: Release ${{ env.new_version }}
        body: |
          This is a new release.
