name: Create Tag on Merge to test

on:
  pull_request:
    types: [closed]
    branches:
      - test

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'test'
    
    steps:
      - name: Create tag
        run: |
          git tag $(cat ./VERSION)
          git push origin $(cat ./VERSION)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

