name: Create Tag on Merge to test

on:
  # push:
  #   branches:
  #     - test
  pull_request:
    types: [closed]
    branches:
      - test

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'test'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: git tag
      run: |
        # # git config user.name "${{ github.actor }}"
        # # git config user.email "${{ github.actor }}@users.noreply.github.com"
        git tag -a "$(echo ${{ steps.branch.outputs.branch_name }} | sed -e 's/release/v/')-$(date +'%Y%m%d%H%M%S')" -m "Tagging $(echo ${{ steps.branch.outputs.branch_name }} | sed -e 's/release/v/')"
        git push --follow-tags
