name: Create Tag on Merge to test

on:
  pull_request:
    types: [closed]
    branches:
      - test

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'test'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Read version from file
        id: Read-version
        run: |
          export VERSION=$(cat ./VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag if not exists
        run: |          
          if git rev-parse ${{ steps.Read-version.outputs.VERSION }} >/dev/null 2>&1; then
            echo "Tag ${{ steps.Read-version.outputs.VERSION }} already exists"
          else
            git tag -a ${{ steps.Read-version.outputs.VERSION }} -m "Updated tag"
            git push origin ${{ steps.Read-version.outputs.VERSION }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
